version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  tests:
    jobs:
      - build
      - test:
          requires:
            - build
